### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CarvalhoLO** [mattmezza/email-sender#10]
Hi,

I am trying to use your email-sender and I found some errors.

Traceback (most recent call last):
  File "email-sender.py", line 165, in <module>
    main(sys.argv[1:])
  File "email-sender.py", line 154, in main
    mailer = MyMailer(config_file, emails_file)
  File "email-sender.py", line 36, in __init__
    self.build_emails()
  File "email-sender.py", line 40, in build_emails
    for entry in self.emails["emails"]:
AttributeError: MyMailer instance has no attribute 'emails'

Could you give me some assistence?

[ ],

Leonardo Carvalho

**Comment by mattmezza** [comment]
Hello @CarvalhoLO 
probably you are using the tool in a wrong way.

Be sure to use it in this way

```
python email-sender.py -c config.yml -e emails.yml
```

If you wanna use it interactively just add `-i` at the end

```
python email-sender.py -c config.yml -e emails.yml -i
```

where config.yml is the config file and emails.yml is the file containing all the email specifications.

With the `-i` param the software will ask you on a per email basis whether or not to send the message. It will show recipient and subject.

**Comment by mattmezza** [comment]
Let me know if I helped you out or not 👍

**Comment by CarvalhoLO** [comment]
root@Lion:/home/leonardo/Desktop/email-sender# python email-sender.py -c config.yml -e emails.yml -i
Error loading file:  [Errno 2] No such file or directory: 'config.yml'
Traceback (most recent call last):
  File "email-sender.py", line 230, in <module>
    main(sys.argv[1:])
  File "email-sender.py", line 219, in main
    mailer = MyMailer(config_file, emails_file, log_file)
  File "email-sender.py", line 47, in __init__
    self.build_emails()
  File "email-sender.py", line 52, in build_emails
    tot = len(self.emails["emails"])
AttributeError: MyMailer instance has no attribute 'emails'

I am trying to use these new codes and terminal gives me that errors.

**Comment by mattmezza** [comment]
You need to create a file config.yml and emails.yml based on the examples provided in config.sample.yml and emails.sample.yml. 



___________________________________
This email looks weird??? That's because it's sent from my mobile... 😉 ;-)

On Sep 2, 2017, at 10:17 AM, CarvalhoLO <notifications@github.com> wrote:

root@Lion:/home/leonardo/Desktop/email-sender# python email-sender.py -c config.yml -e emails.yml -i
Error loading file: [Errno 2] No such file or directory: 'config.yml'
Traceback (most recent call last):
File "email-sender.py", line 230, in 
main(sys.argv[1:])
File "email-sender.py", line 219, in main
mailer = MyMailer(config_file, emails_file, log_file)
File "email-sender.py", line 47, in init
self.build_emails()
File "email-sender.py", line 52, in build_emails
tot = len(self.emails["emails"])
AttributeError: MyMailer instance has no attribute 'emails'

I am trying to use this new codes and terminal gives me that errors.

**Comment by CarvalhoLO** [comment]
Files created and the errors multiply:

root@Lion:/home/leonardo/Desktop/email-sender# python email-sender.py -c config.yml -e emails.yml -i
Error loading file:  while parsing a block mapping
  in "emails.yml", line 1, column 1
expected <block end>, but found '<block sequence start>'
  in "emails.yml", line 23, column 2
Traceback (most recent call last):
  File "email-sender.py", line 230, in <module>
    main(sys.argv[1:])
  File "email-sender.py", line 219, in main
    mailer = MyMailer(config_file, emails_file, log_file)
  File "email-sender.py", line 47, in __init__
    self.build_emails()
  File "email-sender.py", line 52, in build_emails
    tot = len(self.emails["emails"])
AttributeError: MyMailer instance has no attribute 'emails'
root@Lion:/home/leonardo/Desktop/email-sender# python email-sender.py -c config.yml -e emails.yml -i
Error loading file:  while parsing a block mapping
  in "emails.yml", line 1, column 1
expected <block end>, but found '<block sequence start>'
  in "emails.yml", line 23, column 2
Traceback (most recent call last):
  File "email-sender.py", line 230, in <module>
    main(sys.argv[1:])
  File "email-sender.py", line 219, in main
    mailer = MyMailer(config_file, emails_file, log_file)
  File "email-sender.py", line 47, in __init__
    self.build_emails()
  File "email-sender.py", line 52, in build_emails
    tot = len(self.emails["emails"])
AttributeError: MyMailer instance has no attribute 'emails'
root@Lion:/home/leonardo/Desktop/email-sender#

**Comment by CarvalhoLO** [comment]
Files created and erros multiply

root@Lion:/home/leonardo/Desktop/email-sender# python email-sender.py -c config.yml -e emails.yml -i
Error loading file:  while parsing a block mapping
  in "emails.yml", line 1, column 1
expected <block end>, but found '<block sequence start>'
  in "emails.yml", line 23, column 2
Traceback (most recent call last):
  File "email-sender.py", line 230, in <module>
    main(sys.argv[1:])
  File "email-sender.py", line 219, in main
    mailer = MyMailer(config_file, emails_file, log_file)
  File "email-sender.py", line 47, in __init__
    self.build_emails()
  File "email-sender.py", line 52, in build_emails
    tot = len(self.emails["emails"])
AttributeError: MyMailer instance has no attribute 'emails'
root@Lion:/home/leonardo/Desktop/email-sender# python email-sender.py -c config.yml -e emails.yml -i
Error loading file:  while parsing a block mapping
  in "emails.yml", line 1, column 1
expected <block end>, but found '<block sequence start>'
  in "emails.yml", line 23, column 2
Traceback (most recent call last):
  File "email-sender.py", line 230, in <module>
    main(sys.argv[1:])
  File "email-sender.py", line 219, in main
    mailer = MyMailer(config_file, emails_file, log_file)
  File "email-sender.py", line 47, in __init__
    self.build_emails()
  File "email-sender.py", line 52, in build_emails
    tot = len(self.emails["emails"])
AttributeError: MyMailer instance has no attribute 'emails'
root@Lion:/home/leonardo/Desktop/email-sender#

**Comment by mattmezza** [comment]
This clearly states there are some errors in the files you created. 
```
Error loading file: while parsing a block mapping
in "emails.yml", line 1, column 1
```

I suggest http://www.yamllint.com/ to validate the files you create.

**Comment by mattmezza** [comment]
Did it work? Let me know if you need further assistance.
